### ISSUE TITLE
Way to configure the button gap size?

### ISSUE THREAD

**Issue by damieng** [yawor/m4board-enclosure#1]
Hi there, love the case and the files to create them but when I print the front face my buttons are stuck and even a knife isn't going to fix it - there's a gap on the inside of the case but the outside which was against the build plate is solid.

I couldn't see a way to configure the size of the gap around each button from the openscad file. Could that be made into a parameter for such a scenario?

**Comment by yawor** [comment]
Hi,
This is probably printer dependent as I've had no issue printing this on my Prusa Mini.
If you check the `pcb_enclosure.scad` source, you'll see that `PCBEnclosure` module has a `buttonTolerance` argument. It's not being explicitly set from `m4board_*.scad` files so it uses a default value of 0.2 mm. You can either modify a default value in `pcb_enclosure.scad` or add your value in `m4board_*.scad` to `PCBEnclosure()` call.

**Comment by damieng** [comment]
Thanks that looks like it has successfully modified things. I've tried doubling it to 0.4mm and will see how it prints tomorrow.
